name: Build LaTeX

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update && sudo apt-get install -y texlive-base
    - run: make -C "${{ github.workspace }}"
